title: "Omics Integration and Systems Biology Workshop"
description: "Course Website for the Omics Integration and Systems Biology Workshop 2024"
baseurl: "/workshop_omics_integration"
url: "https://nbisweden.github.io"
remote_theme: "mmistakes/minimal-mistakes" # Your chosen theme
author:
  name: "NBIS Sweden"
  email: "edu.omics-integration@nbis.se"
markdown: kramdown
permalink: pretty

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed
custom_css: "assets/css/custom.css"

# Navigation settings
navigation:
  - title: "Home"
    url: "/"
  - title: "Schedule"
    url: "/schedule.html"
  - title: "Pre-course Preparation"
    url: "/precourse.html"
  - title: "Labs"
    url: "/labs.html"
  - title: "Reading Materials"
    url: "/reading_materials.html"
  - title: "Contact"
    url: "/contact.html"
