title: "Workshop howto"
baseurl: /workshop-howto

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url:
  - title: Schedule
    url: schedule
  - title: Pre-course material
    url: precourse
  - title: Travel info
    url: travel
  - title: Labs
    submenus:
      - title: New course
        url: labs/new_course
      - title: Edit course
        url: labs/edit_course
      - title: Quick fix
        url: labs/quick_fix
      - title: Run offline
        url: labs/run_offline
      - title: Archive course
        url: labs/archive_course
      - title: Move scilife course
        url: labs/move_scilife_course
