title: "Test course"
baseurl: /course-test

# where things are
layouts_dir: ./course-common/layouts
includes_dir: ./course-common/includes
sass:
  sass_dir: ./course-common/sass

defaults:
  - values:
      logosnav: true

menu:
  - title: Schedule
    url: schedule
  - title: Labs
    submenus:
      - title: ChIP-seq data processing
        url: labs/processing
      - title: Down-stream analysis
        url: labs/diffBinding
  
