title: "Test course"

# where things are
layouts_dir: ./course-common/layouts
includes_dir: ./course-common/includes
sass:
  sass_dir: ./course-common/sass

defaults:
  - values:
      logosnav: true

menu:
  - title: Schedule
    url: /course-test/schedule
  - title: Labs
    submenus:
      - title: ChIP-seq data processing
        url: /course-test/labs/processing
      - title: Down-stream analysis
        url: /course-test/labs/diffBinding
  
