name: Build and Push Docker Images

on:
  push:
    paths:
      - 'session_gems/**'
      - 'session_ml/**'
      - 'session_meta/**'
      - 'session_topology/**'
    branches:
      - OMICSINT_H24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the images for both amd64 and arm64
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ./  # Change to the appropriate Dockerfile directory dynamically
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/rasoolsnbis/omicsint_h24:${{ github.event.head_commit.id }}

      # Optionally, inspect the image
      - name: Inspect Image
        run: docker buildx imagetools inspect docker.io/rasoolsnbis/omicsint_h24:${{ github.event.head_commit.id }}
