name: myenv
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-plotly
  - r-dplyr
  - r-tidyr
  - r-mixomics
  - bioconductor-mofa2
  - r-reticulate